### ISSUE TITLE
Doesn't work with swift 2.x syntax.

### ISSUE THREAD

**Issue by weaksauce** [brynbellomy/Regex#2]

**Comment by brynbellomy** [comment]
I thought I just finally got this in line with the new syntax ... hrm, I'll look into it this week.

**Comment by weaksauce** [comment]
actually the podspec is just out of date. seems that you just need to up the tag to the latest commit and update the podspec file.

**Comment by brynbellomy** [comment]
Oh, good catch.  I'll do that this evening since it sounds like a really quick fix.

**Comment by brynbellomy** [comment]
@weaksauce Okay — 0.3.0 is live on CocoaPods.  If you have time, give it a spin, and feel free to reopen this issue if you have problems.
